### ISSUE TITLE
Random Distractors in Multi-Document QA

### ISSUE THREAD

**Issue by edixiong** [nelson-liu/lost-in-the-middle#11]
Hi Nelson, Thanks for the great work! I wonder how you get the random distractors (random wikipedia documents) in multi-document qa (in Appendix B).

In particular, in your nq-open-contriever-msmarco-retrieved-documents.jsonl.gz document, for each question, the context documents are collected by the Contriever and the documents are relevant to the question. Is there any code that you would suggest me to check (and modify on) to get random wikipedia document (e.g., to check the code of Contriever), or is it possible for you to share a jsonl.gz file of random wiki documents (if you already have one)?

Thanks in advance!

**Comment by nelson-liu** [comment]
Hi! The random passages are just randomly sampled from the retrieval corpus, which is the DPR-segmented Wikipedia:  ( https://dl.fbaipublicfiles.com/dpr/wikipedia_split/psgs_w100.tsv.gz ).

Regardless, I uploaded a file with queries and randomly-sampled contexts, since that's probably easier for you to use? Let me know if this wasn't what you were looking for: https://nlp.stanford.edu/data/nfliu/lost-in-the-middle/nq-open-random-documents.jsonl.gz

hope that helps!

**Comment by edixiong** [comment]
Thank you, this is exactly what I am looking for!

**Comment by ludalevy** [comment]
Hi Nelson, I have a question.. how do you create the  https://nlp.stanford.edu/data/nfliu/lost-in-the-middle/nq-open-random-documents.jsonl.gz? According to the paper? Did you use contriever-msmarco? Do you have a code of the file builder?
Thanks

**Comment by nelson-liu** [comment]
Hi @ludalevy , the file [nlp.stanford.edu/data/nfliu/lost-in-the-middle/nq-open-random-documents.jsonl.gz](https://nlp.stanford.edu/data/nfliu/lost-in-the-middle/nq-open-random-documents.jsonl.gz) does _not_ use the MSMARCO-trained contriever scores---the distractor passages are just randomly sampled from wikipedia . This file was only used for appendix B.

In contrast, the file https://nlp.stanford.edu/data/nfliu/lost-in-the-middle/nq-open-contriever-msmarco-retrieved-documents.jsonl.gz _does_ use MSMARCO-trained contriever scores. This file / the setup in this file was used for the bulk of the paper experiments (except appendix B)

I still have code to generate these files and can work on releasing them, was there one that you were more interested in? it wasn't clear to me from your comment.

**Comment by ludalevy** [comment]
Hi,
It will be great and helpful for me to see the code of data generation.
Thanx,
Luda
