### ISSUE TITLE
Source and preprocessing of the documents

### ISSUE THREAD

**Issue by GianlucaDeStefano** [nelson-liu/lost-in-the-middle#12]
Hi, thank you for the lovely paper. 

I am curious about the exact source and preprocessing of the documents used to augment the prompt. 
The paper states:
```
We use passages (chunks of at most 100 tokens) from Wikipedia as documents within our input contexts. For each of the queries, we need a document that contains the answer and k − 1 distractor documents that do not contain the answer. To obtain a document that answers the question, we use the Wikipedia paragraph that contains the answer from the NaturalQuestions annotations.
```
And additionally in the Appendix:
```
We use a Wikipedia dump from late 2018 as our retrieval corpus.
```

Can you share the specific Wikipedia dump you used? 
How did you preprocess the documents? Did you filter out HTML tags and such? If yes, could you share the preprocessing script/logic?

Thank you in advance :)

**Comment by nelson-liu** [comment]
Hi @GianlucaDeStefano , for the distractor passages we simply used the set of wikipedia passages used in DPR: https://dl.fbaipublicfiles.com/dpr/wikipedia_split/psgs_w100.tsv.gz --- it's a fairly standard retrieval corpus for a lot of work in this space. I'm not 100% sure what they did in terms of pre-processing, etc, but the DPR paper or repo itself might be a better read in that regard. Looks like the dump is from Dec 20, 2018.

- https://github.com/facebookresearch/dpr
- https://arxiv.org/abs/2004.04906 , section 4.1

Hope that helps!
