### ISSUE TITLE
Comparison with Giraffe

### ISSUE THREAD

**Issue by wutong4012** [nelson-liu/lost-in-the-middle#15]
hi, @nelson-liu , thank you very much for your work.

I see some conflict between your work and the results of [Giraffe: Adventures in Expanding Context Lengths in LLMs.](https://arxiv.org/abs/2308.10882)

What do you think is the cause?

![image](https://github.com/nelson-liu/lost-in-the-middle/assets/41939510/1ded0f9a-737a-4852-8e1f-ed9c02743a3d)

**Comment by nelson-liu** [comment]
Sorry, I haven't read this paper and likely won't have time to dig deeply in the next few weeks. If it helps, I know of at least a few papers that found similar results in different settings (though I haven't really been keeping up with the literature in this space, been thinking about other stuff):

- figure 2 of https://arxiv.org/abs/2310.01427 (a semi-synthetic QA dataset created by the authors)
- sec 4.1 of https://arxiv.org/abs/2310.10570 (summarization, not QA)
- appendix A of https://arxiv.org/abs/2312.01279

I'll put this on the TODO and reply back if I ever get around to reading this paper and thinking through its results, but I'm just a bit overloaded at the moment---apologies. let me know if you have any other questions / hypotheses.
