### ISSUE TITLE
Evaluation metric code

### ISSUE THREAD

**Issue by Tan-Hexiang** [nelson-liu/lost-in-the-middle#2]
Hi!
Do you have any plan to release the code of evaluation metric **accuracy**.  I am trying to reproduce the experiment. The **accuracy** has some difference calculating method with small difference like nomalize.

**Comment by nelson-liu** [comment]
Hi! Good question, I'm happy to release that. Sorry, i want to add a bunch more stuff to this codebase, but haven't had time with traveling to ACL.

For more details on the metric, we first normalized via the SQuAD normalization function:

```
import string

def normalize_answer(s: str) -> str:
    """Normalization from the SQuAD evaluation script.

    See https://worksheets.codalab.org/rest/bundles/0x6b567e1cf2e041ec80d7098f031c5c9e/contents/blob/
    """

    def remove_articles(text):
        return regex.sub(r"\b(a|an|the)\b", " ", text)

    def white_space_fix(text):
        return " ".join(text.split())

    def remove_punc(text):
        exclude = set(string.punctuation)
        return "".join(ch for ch in text if ch not in exclude)

    def lower(text):
        return text.lower()

    return white_space_fix(remove_articles(remove_punc(lower(s))))
```

Then, we compute accuracy as:

```
def accuracy(prediction: str, ground_truths: List[str], **kwargs) -> float:
    """
    Given a prediction and a list of ground truths, compute max accuracy of
    any token span of the prediction.
    """
    normalized_prediction = normalize_answer(prediction)

    for ground_truth in ground_truths:
        normalized_ground_truth = normalize_answer(ground_truth)
        if normalized_ground_truth.lower() in normalized_prediction.lower():
            return 1.0
    return 0.0
```

Does that answer your question?

Also, I'd love to hear more about whether you were able to broadly reproduce the results.

**Comment by Tan-Hexiang** [comment]
Thanks very much! This will help me a lot.

**Comment by Tan-Hexiang** [comment]
Hi!
I noticed that all the experimental results in the article are presented in the form of line graphs. While this effectively showcases the trends, the specific values are not labeled on the graphs. If possible, it would be best to provide detailed data in tabular form in the GitHub project as well. This would make it easier for replication and comparison.

**Comment by nelson-liu** [comment]
yes, i can work on this, thanks for the suggestion.

**Comment by nelson-liu** [comment]
Here's the data behind Figure 5 as a table:

![image](https://github.com/nelson-liu/lost-in-the-middle/assets/7272031/cdd75f00-3230-45e5-af6b-b98fd90f3e23)

Index 0 means that the relevant information is placed at the very start of the context. Higher index = more towards the end of the context (and thus closer to the point of generation).

Hope that helps! Feel free to re-open if you have any other questions.
