### ISSUE TITLE
Reproduce Code

### ISSUE THREAD

**Issue by Jinhyeong-Lim** [nelson-liu/lost-in-the-middle#3]
Hi
I find your research incredibly fascinating. 
I appreciate you sharing your excellent research and code. 
Could you please share the code you used for experiments with longchat-13B?
It would be tremendously helpful for reproducing the experiments
Thank you

**Comment by nelson-liu** [comment]
I can work on this, it might take me a few weeks though---sorry for the delay. I expect it should be reasonably straightforward to implement it yourself by pip installing the longchat repo ( https://github.com/DachengLi1/LongChat ) and running the model with HF transformers.

**Comment by Jinhyeong-Lim** [comment]
It would be very helpful if you could find and share the code. Thank you!
Then, could you provide information about the generate config? 
For example, temperature, max_new_tokens, etc.

**Comment by nelson-liu** [comment]
We use greedy decoding (i.e., no sampling with temperature or top-p). max_new_tokens is set to 100.

**Comment by nelson-liu** [comment]
I added some scripts and instructions to run and evaluate MPT and LongChat, please let me know if you have any issues.
