### ISSUE TITLE
how does you truncate the input when the input_length is longer than model's context length.

### ISSUE THREAD

**Issue by eyuansu62** [nelson-liu/lost-in-the-middle#6]
For example, chatgpt has 4k token context and if the answer position is at 20th of the document, it would exceed the 4k in some cases.

**Comment by nelson-liu** [comment]
We don't do any truncation. Appendix F in the paper (version 2, I put this on arxiv on the July 31st) has token counts for each of the models on each of the settings (reproduced below). Note that for 20 docs, the max context length with the OpenAI tokenizer is 3920, which is within the 4096 gpt-3.5-turbo context so we don't need to truncate.

![image](https://github.com/nelson-liu/lost-in-the-middle/assets/7272031/829c3d0b-53ae-4bf4-acf0-129b984610ef)

I'm going to close this for now, but feel free to follow up with further questions if you have any.

**Comment by eyuansu62** [comment]
have you ever tried other model since maybe other model do not have such behavior

**Comment by nelson-liu** [comment]
I'm not sure I understand the question. [In the paper,](https://cs.stanford.edu/~nfliu/papers/lost-in-the-middle.arxiv2023.pdf) we tried quite a few models:
- openai gpt-3.5-turbo 4k and 16k
- claude and claude 100k
- mpt-30b-instruct / non-instruct
- flan-t5-xxl / flan-ul2
- longchat-13b-16k

Is there a different notion of "other model" that you are thinking about?

**Comment by eyuansu62** [comment]
I tried llama2-7b and llama2-7b-32k on your code and do not find the U-shape. I'm not sure if 7b is too small.

**Comment by nelson-liu** [comment]
Hmm, it's possible. what sort of trends are you seeing? Also, is this the instruction-tuned / chat-tuned model, or just the standard left-to-right LM?

**Comment by nelson-liu** [comment]
To add, I think the llama2-7b tokenizer is very verbose, so even 20 documents don't fit in its context (based on the LongChat tokenized experiments)...not sure what settings you were looking at in particular / if you were applying any truncation, etc.

Lastly, by the 32K model, are you referring to the together model? https://huggingface.co/togethercomputer/LLaMA-2-7B-32K

**Comment by eyuansu62** [comment]
1. The max input length tokenized by the llama2 tokenizer is around 4190 and just 2 cases. 
2. Yes, it is.

**Comment by nelson-liu** [comment]
Hi @eyuansu62 , just wanted to follow up here.

> Lastly, by the 32K model, are you referring to the together model? huggingface.co/togethercomputer/LLaMA-2-7B-32K

note that the together 32K model is actually fine-tuned on our data, so i think it's fairly natural that you wouldn't see the U-shaped performance curve in that setting.

We're preparing an updated version of the paper, and ran some LLaMA-2 experiments. Here's a plot of LLaMA-2 models of varying sizes, with and without additional SFT + RLHF: The results are below:

![image](https://github.com/nelson-liu/lost-in-the-middle/assets/7272031/69d50aad-6aba-4a50-b602-7bd51d5ed3e0)

> I tried llama2-7b and llama2-7b-32k on your code and do not find the U-shape. I'm not sure if 7b is too small.

It seems like your hypothesis about 7B being too small might have been correct---the 7B models (both base and chat) largely only show recency bias, and you only start seeing the U-shape curve when you go to 13B or 70B-parameter models.
